build:
  maxIssues: 0
  excludeCorrectable: false

config:
  validation: true
  checkExhaustiveness: false

processors:
  active: true

console-reports:
  active: true

output-reports:
  active: true

comments:
  active: false

complexity:
  active: false

coroutines:
  active: false

empty-blocks:
  active: false

exceptions:
  active: false

naming:
  active: false

performance:
  active: false

potential-bugs:
  active: false

style:
  active: true
  NewLineAtEndOfFile:
    active: true
  MagicNumber:
    active: false
  MaxLineLength:
    active: false
  UnusedParameter:
    active: false
  UnusedPrivateMember:
    active: false
  WildcardImport:
    active: false
  UseCheckOrError:
    active: false
  ReturnCount:
    active: false
  ThrowsCount:
    active: false
  VarCouldBeVal:
    active: false